### ISSUE TITLE
web端加入iframe，mobile端畫面沒有出來

### ISSUE THREAD

**Issue by haoappwork** [netless-io/Whiteboard-iOS#63]

**Comment by leavesster** [comment]
如果是使用的iframe 插件，需要在初始化房间前，开启 iframe 插件。搜索一下 enableIframe 应该可以找到。

**Comment by haoappwork** [comment]
我測試退回到2.10.0 默認enableIframe為true 跑出來是正常，但使用新版2.16.7 照doc init 並將enableIframe設為true 起不了作用，測試如圖
![2 10 0_ enableIframe_預設開](https://user-images.githubusercontent.com/102138691/159836678-b3c58737-2c1c-434f-99da-beb3a97137b9.png)
![2 16 7_enableIframe_初始設為true](https://user-images.githubusercontent.com/102138691/159836686-35cc2358-d19a-478f-87a4-76d1f77968b2.png)
