### ISSUE TITLE
web端加入iframe，mobile端畫面沒有出來 補上新舊版測試結果圖

### ISSUE THREAD

**Issue by haoappwork** [netless-io/Whiteboard-iOS#66]
我測試退回到2.10.0 默認enableIframe為true 跑出來是正常，但使用新版2.16.7 照doc init 並將enableIframe設為true 起不了作用，測試如圖
![2 10 0_ enableIframe_預設開](https://user-images.githubusercontent.com/102138691/159853186-3acc84ce-9c03-4453-9137-c29e5a3ba141.png)
![2 16 7_enableIframe_初始設為true](https://user-images.githubusercontent.com/102138691/159853199-3681141c-4b56-4c24-8859-2e90d9b48b5a.png)

**Comment by leavesster** [comment]
> 我測試退回到2.10.0 默認enableIframe為true 跑出來是正常，但使用新版2.16.7 照doc init 並將enableIframe設為true 起不了作用，測試如圖 ![2 10 0_ enableIframe_預設開](https://user-images.githubusercontent.com/102138691/159853186-3acc84ce-9c03-4453-9137-c29e5a3ba141.png) ![2 16 7_enableIframe_初始設為true](https://user-images.githubusercontent.com/102138691/159853199-3681141c-4b56-4c24-8859-2e90d9b48b5a.png)

查看下，是否开了 useMultipleView 这个参数呢？
ps: 如果上一个 issue 没有解决，就被 close，您也仍然可以在旧的 issue 上继续附加新信息。

**Comment by haoappwork** [comment]
你好 沒有開啟useMultipleView 單純針對 enableIframe 舊版預設打開與新版必須設置版本做測試比對 發現舊版預設打開 iframe顯示正常 但在新版本設置enableIframe參數為true 並沒有作用

**Comment by vince-hz** [comment]
> 你好 沒有開啟useMultipleView 單純針對 enableIframe 舊版預設打開與新版必須設置版本做測試比對 發現舊版預設打開 iframe顯示正常 但在新版本設置enableIframe參數為true 並沒有作用
> 
> 抱歉，多開了一個issue，那以這篇為主，close那邊相同的issue可以刪除，謝謝。

我们已经定位了这个问题，是新版本对旧的参数兼容性有缺陷，近期会修复。

**Comment by vince-hz** [comment]
已经修复，最迟本周五会发新版本。 2.16.13

**Comment by haoappwork** [comment]
> 已经修复，最迟本周五会发新版本。 2.16.13

我這使用2.16.13 測試畫面有出來了 但感覺iframe出現的位置像是開了多窗口的位置  顯示位置不正確
![截圖 2022-03-29 下午2 01 34](https://user-images.githubusercontent.com/102138691/160544081-e5951772-82c8-4022-91d7-baaa146b501a.png)

**Comment by vince-hz** [comment]
> > 已经修复，最迟本周五会发新版本。 2.16.13
> 
> 我這使用2.16.13 測試畫面有出來了 但感覺iframe出現的位置像是開了多窗口的位置 顯示位置不正確 ![截圖 2022-03-29 下午2 01 34](https://user-images.githubusercontent.com/102138691/160544081-e5951772-82c8-4022-91d7-baaa146b501a.png)

我在本地使用web和iOS最新的相同的版本，测试https://example.org。没有问题
为了排查问题，需要请你帮助提供一下以下内容：
1. 你正在使用的web版本
2. 你插入的iframe地址

**Comment by haoappwork** [comment]
> > > 已经修复，最迟本周五会发新版本。 2.16.13
> > 
> > 
> > 我這使用2.16.13 測試畫面有出來了 但感覺iframe出現的位置像是開了多窗口的位置 顯示位置不正確 ![截圖 2022-03-29 下午2 01 34](https://user-images.githubusercontent.com/102138691/160544081-e5951772-82c8-4022-91d7-baaa146b501a.png)
> 
> 我在本地使用web和iOS最新的相同的版本，测试 https://example.org 没有问题 为了排查问题，需要请你帮助提供一下以下内容：
> 
> 1. 你正在使用的web版本
> 2. 你插入的iframe地址

我們web端使用的是 react-sdk 2.16.1
![image](https://user-images.githubusercontent.com/102138691/160581571-966406f3-aaae-4dbe-a83c-d8dc58275996.png)
0

**Comment by leavesster** [comment]
这种情况，可能跟 web 端的 css 有关。可以一点点先排除 css 影响。

**Comment by haoappwork** [comment]
> 这种情况，可能跟 web 端的 css 有关。可以一点点先排除 css 影响。

跟我這邊web端css有關嗎？ 還是說web react-sdk 可能要更新什麼，因為如一開始我測試的圖，ios sdk 在2.10.0版本是正常顯示
![2 10 0_ enableIframe_預設開](https://user-images.githubusercontent.com/102138691/160592348-a2324f09-f24c-457b-bb64-3ab6896e1d72.png)

**Comment by leavesster** [comment]
这个版本跨度太大，内部结构从 svg 换成了 canvas，这个可能影响了整体 canvas 布局。
在我们这边效果没问题的话，可能是外部的 css 影响。
另外，可以试试 white-web-sdk

**Comment by haoappwork** [comment]
我上面測試 只是ios sdk退回舊版2.10.0 我同步連線的web端使用的還是最新版的sdk 2.16.10 至於用web或react 結果照理說都會一樣，因為你們web跟react都有同步更新到最新版

我覺得主要問題還是查查看ios sdk這邊 我測試起來，感覺目前跑出來的畫面佈局像是使用了useMultipleView 但我這邊並沒有開啟這參數 我甚至初始化 將它設為false 避免干擾，但畫面佈局還是不正確

就測試結果來說 web版本不變 唯一有差的是ios版本 再麻煩你們排查看看
另外andorid那邊也要麻煩你們看看 android測試的結果 一樣是iframe沒出來 允許iframe插件那參數無作用

**Comment by vince-hz** [comment]
> 我上面測試 只是ios sdk退回舊版2.10.0 我同步連線的web端使用的還是最新版的sdk 2.16.10 至於用web或react 結果照理說都會一樣，因為你們web跟react都有同步更新到最新版
> 
> 我覺得主要問題還是查查看ios sdk這邊 我測試起來，感覺目前跑出來的畫面佈局像是使用了useMultipleView 但我這邊並沒有開啟這參數 我甚至初始化 將它設為false 避免干擾，但畫面佈局還是不正確
> 
> 就測試結果來說 web版本不變 唯一有差的是ios版本 再麻煩你們排查看看 另外andorid那邊也要麻煩你們看看 android測試的結果 一樣是iframe沒出來 允許iframe插件那參數無作用

方便把你插入的iframe网页的地址提供一下吗？不然我们不太方便重现你所描述的错误。
我的邮箱是 xuyunshi@agora.io

安卓的问题等我们这边解决完了，会同步更新的。

**Comment by haoappwork** [comment]
> > 我上面測試 只是ios sdk退回舊版2.10.0 我同步連線的web端使用的還是最新版的sdk 2.16.10 至於用web或react 結果照理說都會一樣，因為你們web跟react都有同步更新到最新版
> > 我覺得主要問題還是查查看ios sdk這邊 我測試起來，感覺目前跑出來的畫面佈局像是使用了useMultipleView 但我這邊並沒有開啟這參數 我甚至初始化 將它設為false 避免干擾，但畫面佈局還是不正確
> > 就測試結果來說 web版本不變 唯一有差的是ios版本 再麻煩你們排查看看 另外andorid那邊也要麻煩你們看看 android測試的結果 一樣是iframe沒出來 允許iframe插件那參數無作用
> 
> 方便把你插入的iframe网页的地址提供一下吗？不然我们不太方便重现你所描述的错误。 我的邮箱是 [xuyunshi@agora.io](mailto:xuyunshi@agora.io)
> 
> 安卓的问题等我们这边解决完了，会同步更新的。

已寄信，再麻煩排查

**Comment by vince-hz** [comment]
> > > 我上面測試 只是ios sdk退回舊版2.10.0 我同步連線的web端使用的還是最新版的sdk 2.16.10 至於用web或react 結果照理說都會一樣，因為你們web跟react都有同步更新到最新版
> > > 我覺得主要問題還是查查看ios sdk這邊 我測試起來，感覺目前跑出來的畫面佈局像是使用了useMultipleView 但我這邊並沒有開啟這參數 我甚至初始化 將它設為false 避免干擾，但畫面佈局還是不正確
> > > 就測試結果來說 web版本不變 唯一有差的是ios版本 再麻煩你們排查看看 另外andorid那邊也要麻煩你們看看 android測試的結果 一樣是iframe沒出來 允許iframe插件那參數無作用
> > 
> > 
> > 方便把你插入的iframe网页的地址提供一下吗？不然我们不太方便重现你所描述的错误。 我的邮箱是 [xuyunshi@agora.io](mailto:xuyunshi@agora.io)
> > 安卓的问题等我们这边解决完了，会同步更新的。
> 
> 已寄信，再麻煩排查

已经修复了，近期会安排发版。感谢提供信息
