### ISSUE TITLE
whiteboard sdk join room error

### ISSUE THREAD

**Issue by zilaiyedaren** [netless-io/Whiteboard-iOS#83]
Optional(Error Domain=com.herewhite.white Code=-100 "file:///var/containers/Bundle/Application/xxxxxxxxxxxxxxxxx/xxx.app/Whiteboard.bundle/netless.27f1f56a.js:242:166716

**Comment by vince-hz** [comment]
> Optional(Error Domain=com.herewhite.white Code=-100 "file:///var/containers/Bundle/Application/xxxxxxxxxxxxxxxxx/xxx.app/Whiteboard.bundle/netless.27f1f56a.js:242:166716

确认一下是否已经执行 `pod install `
如果仍然有问题请提供一下更详细的日志
